name: raw-replay
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: raw-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: demo-data-source
